services:
  commvault-exporter:
    image: commvault_exporter:v1.0
    container_name: commvault-exporter-app 
    restart: unless-stopped

    ports:
      - "9657:9657"

    volumes:
      # Mount the local config directory into the container (read-only recommended)
      # IMPORTANT: You MUST have a ./config/config.yaml file locally relative to this docker-compose.yaml
      - ./config:/app/config:ro