# Multi-target configuration example
targets:
  172.17.207.19:
    api_url: "https://commvault-api/webconsole/api"
    username: "user"
    password: "password"
    verify_ssl: false


exporter:
  port: 9657
  log_level: "INFO"
  timeout: 30